apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toys-bestseller
  description: Toys Best Seller
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=toys-bestseller'
spec:
  type: service
  providesApis:
   - tanzu-java-web-app-api
  consumesApis:
   - demo-api
  lifecycle: experimental
  owner: dev-team-01
  system: springone-tour
