spring:
  application:
    name: toys-bestseller
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"  
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      
springdoc:
  version: 1.0.0
  api-docs.path: /v3/api-docs
  #swagger-ui.path: /swagger-ui.html

# server:
#   port: 8081
#   shutdown: graceful

# spring:
#   application:
#     name: toys-bestseller
#   config:
#     activate:
#       on-profile: default
#     import: configserver:http://localhost:8888

# ---
# server:
#   port: 8081
#   shutdown: graceful
# wavefront:
#   application:
#     service: toys-bestseller
# management:
#   endpoints:
#     health:
#       probes:
#         enabled: true
#     web:
#       exposure:
#         include: '*'
#   #server:
#   #  port: 8081
# spring:
#   application:
#     name: toys-bestseller
#   lifecycle:
#     timeout-per-shutdown-phase: "10s"
#   config:
#     activate:
#       on-profile: kubernetes
#       on-cloud-platform: kubernetes
#     import: configserver:http://spring-cloud-kubernetes-configserver:8888
#   cloud:
#     kubernetes:
#       configserver:
#         config-map-namespaces:
#       enabled: true
#       discovery:
#         discovery-server-url: http://spring-cloud-kubernetes-discoveryserver
#         all-namespaces: true


# ---
# spring:
#   profiles:
#     group:
#       kubernetes-group:
#         - git
#         - kubernetes