apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSource
metadata:
  name: sc-config-source
  namespace: dev-team-01
spec:
  backends:
    - type: git
      #uri: https://github.com/haewons-tanzu/spring-cloud-k8s-config
      uri: https://github.com/spring-cloud-services-samples/cook-config

---
apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSlice
metadata:
  name: sc-config-slice
  namespace: dev-team-01
spec:
  configurationSource: sc-config-source
  content:
  - cook/default
  - cook/production
  - dessert/default/tap
  - secretmenu/default/tap

---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: sc-config-claim
  namespace: dev-team-01
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: sc-config-slice
    namespace: dev-team-01