apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSource
metadata:
  name: sc-config-source
  namespace: dev-team-01
spec:
  backends:
    - type: git
      uri: https://github.com/haewons-tanzu/spring-cloud-k8s-config
      #secretRef: 
      #  name: new-git-secret
      #  namespace: <namespace>

---
apiVersion: "config.apps.tanzu.vmware.com/v1alpha4"
kind: ConfigurationSlice
metadata:
  name: sc-config-slice
  namespace: dev-team-01
spec:
  configurationSource: sc-config-source
  content:  
  - fashion-bestseller
  - fashion-bestseller/default/master
  - toys-bestseller/default/master
  - hot-deals/default/master
  interval: 5s

---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: sc-config-claim
  namespace: dev-team-01
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: sc-config-slice
    namespace: dev-team-01