apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: my-gateway
  namespace: dev-team-01
  labels:
    app.kubernetes.io/part-of: fashion-bestseller
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8090"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway
    tanzu.app.live.view.application.actuator.path: actuator
    tanzu.app.live.view.application.name: my-gateway
    
spec:
  observability:
    metrics:
      prometheus:
        enabled: true
  count: 2
  api:
    title: My Exciting APIs
    description: Lots of new exciting APIs for you to use!
    version: 0.1.0
    serverUrl: https://my-gateway.dev-team-01.tap.tanzukorea.xyz
  #env:
  #  - name: spring.cloud.gateway.httpclient.connect-timeout
  #    value: 90000

---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: sc-route-config
  namespace: dev-team-01
spec:
  service:
    name: my-gateway
  routes:
  - uri: http://fashion-bestseller.dev-team-01.svc.cluster.local
    # https://fashion-bestseller.dev-team-01.tap.tanzukorea.xyz/fashion/bestseller
    predicates: 
    - Path=/fashion-bestseller/**
  - uri: http://toys-bestseller.dev-team-01.svc.cluster.local
    # https://toys-bestseller.dev-team-01.tap.tanzukorea.xyz/toys/bestseller
    predicates: 
    - Path=/hotdeals/**
  - uri: http://hot-deals.dev-team-01.svc.cluster.local
    # https://hot-deals.dev-team-01.tap.tanzukorea.xyz/hotdeals
    predicates: 
    - Path=/fashion-bestseller/**
  # - predicates:
  #   - Path=/api/public/**
  #   filters:
  #   - StripPrefix=2
  
  # - uri: https://httpbin.org
  #   predicates:
  #   - Path=/httpbin/**
  #   filters:
  #   - AddRequestHeader=X-Request-Extra, Hello from Spring Cloud Gateway!

---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: sc-tap-mapping
  namespace: dev-team-01
spec:
  gatewayRef:
    name: my-gateway
    namespace: dev-team-01
  routeConfigRef:
    name: sc-route-config

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-gateway-ingress
  namespace: dev-team-01
  labels:
    app: my-gateway-ingress
spec:
  # tls:
  # - hosts:
  #   - my-gateway.dev-team-01.tap.tanzukorea.xyz
  #   secretName: tap-ingress-selfsigned-root-ca
  # rules:
  # - host: my-gateway.dev-team-01.tap.tanzukorea.xyz
  #   http: 
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: my-gateway
  #           port:
  #             number: 80

  defaultBackend:
    service:
      name: my-gateway
      port:
        number: 80