apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gateway
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: gateway
    apps.tanzu.vmware.com/has-tests: "true"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: gateway
    #networking.knative.dev/visibility: cluster-local
    #apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  # - name: api_descriptor
  #   value:
  #     type: openapi
  #     location:
  #       path: "/v3/api-docs"
  #     system: dev
  #     owner: team-a
  #     description: "A set of API endpoints."
    #- name: BP_GRADLE_BUILT_MODULE
    #  value: "greeter-messages"
  source:
    git:
      url: https://github.com/haewons-tanzu/spring-cloud-tap-demo
      ref:
        branch: master
    subPath: gateway
  env:
    - name: SPRING_CONFIG_IMPORT
    #  value: "optional:configserver:"
      value: "optional:configtree:${SERVICE_BINDING_ROOT}/spring-properties/"
    - name: SPRING_CLOUD_CONFIG_ENABLED
      value: "false"
    - name: SPRING_PROFILES_ACTIVE
      value: "default"
      #value: "production"
  serviceClaims:
    - name: spring-properties
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: sc-config-claim
  